version: "3.7"

services:
  app:
    depends_on:
      - db
    build: ./firetruck
    ports:
      - 8000:80
    environment:
      DB_HOST: db:3306
      DB_NAME:
      DB_USER:
      DB_PASS:
    volumes:
      - ./firetruck/:/var/www/html/

  db:
    image: mysql
    volumes:
      - ./db:/share
      - ./seed:/seed
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    expose:
      - 3306
