version: "3.7"

services:

  frontend:
    image: node:18-alpine
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      VITE_MAILING_LIST_ID: cf2a3ab9-e4cb-4f83-9221-a040736f9172

  backend:
    image: node:18-alpine
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    environment:
      MONGODB_URI: mongodb://backend_db:27017/backend
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING


  backend_db:
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  listmonk:
    ports:
      - 9000:9000
    networks:
      - listmonk
    volumes:
      - ./listmonk/config.toml:/listmonk/config.toml

  listmonk_db:
    ports:
      - 9432:5432
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  firetruck:
    container_name: firetruck
    depends_on:
      - old_db
    build: ./firetruck
    ports:
      - 8000:80
    env_file:
      - ./.env
    environment:
      OLD_DB_HOST: old_db:3306
      OLD_DB_NAME:
      OLD_DB_USER:
      OLD_DB_PASS:
    volumes:
      - ./firetruck/:/var/www/html/
  
  old_db:
    container_name: old_db
    image: mysql
    env_file:
      - ./.env
    volumes:
      - ./old_db/:/share/
    environment:
      MYSQL_ROOT_PASSWORD: ${OLD_DB_ROOT_PASS}
      MYSQL_DATABASE: ${OLD_DB_NAME}
      MYSQL_USER: ${OLD_DB_USER}
      MYSQL_PASSWORD: ${OLD_DB_PASS}
    expose:
      - 3306

networks:
  listmonk:

volumes:
  mongo-data:
  listmonk-data:
