version: "3.7"

services:
  app:
    depends_on:
      - db
    build:
      context: ./firetruck
    expose:
      - 80
    networks:
      - traefik
      - default
    environment:
      DB_HOST: db:3306
      DB_NAME:
      DB_USER:
      DB_PASS:
    labels:
      - traefik.enable=true
      - traefik.http.routers.firetruck.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.firetruck.entrypoints=websecure
      - traefik.http.routers.firetruck.tls=true
      - traefik.http.routers.firetruck.tls.certresolver=letsencrypt
      - traefik.docker.network=traefik
    restart: always
  
  db:
    image: mysql
    expose:
      - 3306
    container_name: DB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed:/seed

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    restart: always

volumes:
  mysql_data:

networks:
  traefik:
    name: traefik
    external: true
