# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.7"

services:

  frontend:
    container_name: frontend
    image: node:18-alpine
    ports:
      - 5173:5173
    volumes:
      - ./frontend/:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development

  db:
    container_name: listmonk_db
    image: postgres:13
    ports:
      - "9432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    container_name: listmonk_app
    # restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    networks:
      - listmonk
    environment:
      - TZ=Etc/UTC
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml

networks:
  listmonk:

volumes:
  listmonk-data:
